# Indicate the CI/CD Pipeline stages of the project.
stages:
    - build
    - deploy

build employee management app angular:
    stage: build
    image: node:18-alpine3.17
    script:
      - npm install
      - echo "Starting Application build stage."
      - ./node_modules/.bin/ng version
      - echo "Building the application."
      - ./node_modules/.bin/ng build
    artifacts:
      paths:
        - dist/employee-management-app-angular/
      expire_in: "3 minutes"

deploy application to aws:
    stage: deploy
    image:
      name: amazon/aws-cli:2.9.0
      entrypoint: [""]
    script:
      - aws --version
      - aws s3 sync dist/employee-management-app-angular/ s3://$AWS_S3_BUCKET --delete
      - echo "Create Amazon CloudFront invalidations for the 2 distributions."
      - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_NOSUBDOMAIN_DISTRIBUTION_ID --paths "/*"
      - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_WWW_DISTRIBUTION_ID --paths "/*"